# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user_data',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='decription',
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='job_decription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='required_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
    ]
