# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20180228_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.SmallIntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('employer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.Employer')),
            ],
        ),
    ]
