# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_employeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeraddress',
            name='employer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='employers.Employer'),
            preserve_default=False,
        ),
    ]
