# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_auto_20180228_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeraddress',
            old_name='employer',
            new_name='company',
        ),
    ]
