# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_auto_20180228_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeraddress',
            old_name='company',
            new_name='employer',
        ),
    ]
