# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_auto_20180228_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='uploader',
            new_name='employer',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='required_experience',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='listing',
            name='job_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
