# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_auto_20180228_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='job_title',
        ),
    ]
