# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_auto_20180228_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
