# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_auto_20180228_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='charge_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
