# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0012_confirmlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmlisting',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
    ]
