# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0013_auto_20180301_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
