# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.SmallIntegerField(null=True),
        ),
    ]
