# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_addressmanager_resumemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressManager',
        ),
        migrations.DeleteModel(
            name='ResumeManager',
        ),
    ]
