# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180227_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='user_resume',
        ),
    ]
