# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180227_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='time_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='time_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skills',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
