# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_resume_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='listings',
            field=models.ManyToManyField(related_name='user_resumes', to='employers.Listing'),
        ),
    ]
