# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180228_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_level',
        ),
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
